/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.AccountController;
import core.controllers.ListAccountsController;
import core.controllers.ListTransactionsController;
import core.controllers.ListUsersController;
import core.controllers.TransactionController;
import core.controllers.UserController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.models.transaction.TransactionType;
import core.models.Account;
import core.models.User;
import core.models.transaction.Transaction;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edangulo
 */
public class BankFrame extends javax.swing.JFrame {
    
    private ArrayList<Account> accounts;
    private ArrayList<Transaction> transactions;
    private ArrayList<User> users;
    
    /**
     * Creates new form BankFrame
     */
    public BankFrame() {
        initComponents();
        this.accounts = new ArrayList<>();
        this.transactions = new ArrayList<>();
        this.users = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsTabbedPane = new javax.swing.JTabbedPane();
        registerUserPanel = new javax.swing.JPanel();
        registerUserLabel = new javax.swing.JLabel();
        registerUserIDLabel = new javax.swing.JLabel();
        registerUserFirstnameLabel = new javax.swing.JLabel();
        registerUserLastnameLabel = new javax.swing.JLabel();
        registerUserAgeLabel = new javax.swing.JLabel();
        regisUserIDTextField = new javax.swing.JTextField();
        regisUserFirstnameTextField = new javax.swing.JTextField();
        regisUserLastnameTextField = new javax.swing.JTextField();
        regisUserAgeTextField = new javax.swing.JTextField();
        regisUserRegisterButton = new javax.swing.JButton();
        createAccountPanel = new javax.swing.JPanel();
        createAccountLabel = new javax.swing.JLabel();
        createAccountUserIDLabel = new javax.swing.JLabel();
        createAccountInitialBalanceLabel = new javax.swing.JLabel();
        cAccountIDTextField = new javax.swing.JTextField();
        cAccountInitBalanTextField = new javax.swing.JTextField();
        cAccountCreateButton = new javax.swing.JButton();
        makeTransactionPanel = new javax.swing.JPanel();
        makeTransactionLabel = new javax.swing.JLabel();
        makeTransacTypeLabel = new javax.swing.JLabel();
        makeTransacSourAccoLabel = new javax.swing.JLabel();
        makeTransacDestAccoLabel = new javax.swing.JLabel();
        makeTransacAmountLabel = new javax.swing.JLabel();
        mTransacSourAccTextField = new javax.swing.JTextField();
        mTransacDestAccTextField = new javax.swing.JTextField();
        mTransacAmountTextField = new javax.swing.JTextField();
        mTransacTypeButton = new javax.swing.JComboBox<>();
        mTransacExecuteButton = new javax.swing.JButton();
        listUsersPanel = new javax.swing.JPanel();
        listUsersLabel = new javax.swing.JLabel();
        listUsersScrollPane = new javax.swing.JScrollPane();
        listUsersTable = new javax.swing.JTable();
        listUsersRefreshButton = new javax.swing.JButton();
        listAccountsPanel = new javax.swing.JPanel();
        listAccountsLabel = new javax.swing.JLabel();
        listAccountsScrollPane = new javax.swing.JScrollPane();
        listAccountsTable = new javax.swing.JTable();
        listAccountsRefreshButton = new javax.swing.JButton();
        listTransactionsPanel = new javax.swing.JPanel();
        listTransactionsLabel = new javax.swing.JLabel();
        listTransactionsScrollPane = new javax.swing.JScrollPane();
        listTransactionsTable = new javax.swing.JTable();
        listTransactioRefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerUserLabel.setText("Register User");

        registerUserIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerUserIDLabel.setText("ID");

        registerUserFirstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerUserFirstnameLabel.setText("Firstname");

        registerUserLastnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerUserLastnameLabel.setText("Lastname");

        registerUserAgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerUserAgeLabel.setText("Age");

        regisUserIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisUserIDTextFieldActionPerformed(evt);
            }
        });

        regisUserLastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisUserLastnameTextFieldActionPerformed(evt);
            }
        });

        regisUserAgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisUserAgeTextFieldActionPerformed(evt);
            }
        });

        regisUserRegisterButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        regisUserRegisterButton.setText("Register");
        regisUserRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisUserRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerUserPanelLayout = new javax.swing.GroupLayout(registerUserPanel);
        registerUserPanel.setLayout(registerUserPanelLayout);
        registerUserPanelLayout.setHorizontalGroup(
            registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserPanelLayout.createSequentialGroup()
                .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerUserPanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(registerUserLabel)
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addGroup(registerUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerUserFirstnameLabel)
                            .addComponent(registerUserLastnameLabel)
                            .addComponent(registerUserAgeLabel)
                            .addComponent(registerUserIDLabel))
                        .addGap(18, 18, 18)
                        .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regisUserIDTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regisUserLastnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regisUserAgeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regisUserFirstnameTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(registerUserPanelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(regisUserRegisterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerUserPanelLayout.setVerticalGroup(
            registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(registerUserLabel)
                .addGap(18, 18, 18)
                .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserIDLabel))
                .addGap(18, 18, 18)
                .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisUserFirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserFirstnameLabel))
                .addGap(18, 18, 18)
                .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisUserLastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserLastnameLabel))
                .addGap(18, 18, 18)
                .addGroup(registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisUserAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserAgeLabel))
                .addGap(18, 18, 18)
                .addComponent(regisUserRegisterButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        tabsTabbedPane.addTab("Register User", registerUserPanel);

        createAccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createAccountLabel.setText("Create Account");

        createAccountUserIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createAccountUserIDLabel.setText("User ID");

        createAccountInitialBalanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createAccountInitialBalanceLabel.setText("Initial Balance");

        cAccountCreateButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cAccountCreateButton.setText("Create");
        cAccountCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAccountCreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(createAccountLabel))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccountUserIDLabel)
                            .addComponent(createAccountInitialBalanceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cAccountInitBalanTextField)
                            .addComponent(cAccountIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(cAccountCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createAccountPanelLayout.setVerticalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(createAccountLabel)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountUserIDLabel))
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountInitBalanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountInitialBalanceLabel))
                .addGap(18, 18, 18)
                .addComponent(cAccountCreateButton)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        tabsTabbedPane.addTab("Create Account", createAccountPanel);

        makeTransactionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        makeTransactionLabel.setText("Make Transaction");

        makeTransacTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makeTransacTypeLabel.setText("Type");

        makeTransacSourAccoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makeTransacSourAccoLabel.setText("Source Account");

        makeTransacDestAccoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makeTransacDestAccoLabel.setText("Destination Account");

        makeTransacAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makeTransacAmountLabel.setText("Amount");

        mTransacDestAccTextField.setToolTipText("");

        mTransacTypeButton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw", "Transfer" }));
        mTransacTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTransacTypeButtonActionPerformed(evt);
            }
        });

        mTransacExecuteButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mTransacExecuteButton.setText("Execute");
        mTransacExecuteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTransacExecuteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makeTransactionPanelLayout = new javax.swing.GroupLayout(makeTransactionPanel);
        makeTransactionPanel.setLayout(makeTransactionPanelLayout);
        makeTransactionPanelLayout.setHorizontalGroup(
            makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeTransactionPanelLayout.createSequentialGroup()
                .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeTransactionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeTransacTypeLabel)
                            .addComponent(makeTransacAmountLabel)
                            .addComponent(makeTransacDestAccoLabel)
                            .addComponent(makeTransacSourAccoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mTransacDestAccTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mTransacSourAccTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mTransacTypeButton, 0, 485, Short.MAX_VALUE)
                            .addComponent(mTransacAmountTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(makeTransactionPanelLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(makeTransactionLabel)))
                .addContainerGap())
            .addGroup(makeTransactionPanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(mTransacExecuteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makeTransactionPanelLayout.setVerticalGroup(
            makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeTransactionPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(makeTransactionLabel)
                .addGap(18, 18, 18)
                .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTransacTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeTransacTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTransacSourAccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeTransacSourAccoLabel))
                .addGap(18, 18, 18)
                .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTransacDestAccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeTransacDestAccoLabel))
                .addGap(18, 18, 18)
                .addGroup(makeTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTransacAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeTransacAmountLabel))
                .addGap(18, 18, 18)
                .addComponent(mTransacExecuteButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        tabsTabbedPane.addTab("Make Transaction", makeTransactionPanel);

        listUsersLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listUsersLabel.setText("List Users");

        listUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Age", "Number of Accounts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listUsersScrollPane.setViewportView(listUsersTable);

        listUsersRefreshButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        listUsersRefreshButton.setText("Refresh");
        listUsersRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUsersRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listUsersPanelLayout = new javax.swing.GroupLayout(listUsersPanel);
        listUsersPanel.setLayout(listUsersPanelLayout);
        listUsersPanelLayout.setHorizontalGroup(
            listUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listUsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listUsersPanelLayout.createSequentialGroup()
                        .addComponent(listUsersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(listUsersPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(listUsersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listUsersRefreshButton)
                        .addGap(88, 88, 88))))
        );
        listUsersPanelLayout.setVerticalGroup(
            listUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listUsersPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(listUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listUsersLabel)
                    .addComponent(listUsersRefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listUsersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsTabbedPane.addTab("List Users", listUsersPanel);

        listAccountsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listAccountsLabel.setText("List Accounts");

        listAccountsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "User ID", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listAccountsScrollPane.setViewportView(listAccountsTable);

        listAccountsRefreshButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        listAccountsRefreshButton.setText("Refresh");
        listAccountsRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAccountsRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listAccountsPanelLayout = new javax.swing.GroupLayout(listAccountsPanel);
        listAccountsPanel.setLayout(listAccountsPanelLayout);
        listAccountsPanelLayout.setHorizontalGroup(
            listAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listAccountsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listAccountsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(listAccountsPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(listAccountsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listAccountsRefreshButton)
                .addGap(90, 90, 90))
        );
        listAccountsPanelLayout.setVerticalGroup(
            listAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listAccountsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(listAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listAccountsLabel)
                    .addComponent(listAccountsRefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listAccountsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsTabbedPane.addTab("List Accounts", listAccountsPanel);

        listTransactionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listTransactionsLabel.setText("List Transactions");

        listTransactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Source Account ID", "Destination Account ID", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTransactionsScrollPane.setViewportView(listTransactionsTable);

        listTransactioRefreshButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        listTransactioRefreshButton.setText("Refresh");
        listTransactioRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTransactioRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listTransactionsPanelLayout = new javax.swing.GroupLayout(listTransactionsPanel);
        listTransactionsPanel.setLayout(listTransactionsPanelLayout);
        listTransactionsPanelLayout.setHorizontalGroup(
            listTransactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTransactionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listTransactionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(listTransactionsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(listTransactionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listTransactioRefreshButton)
                .addGap(89, 89, 89))
        );
        listTransactionsPanelLayout.setVerticalGroup(
            listTransactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTransactionsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(listTransactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listTransactionsLabel)
                    .addComponent(listTransactioRefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listTransactionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsTabbedPane.addTab("List Transactions", listTransactionsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisUserRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisUserRegisterButtonActionPerformed
        // TODO add your handling code here:
        try {
            String id = regisUserIDTextField.getText();
            String firstname = regisUserFirstnameTextField.getText();
            String lastname = regisUserLastnameTextField.getText();
            String age = regisUserAgeTextField.getText();
            
            Response response = UserController.registerUser(id, firstname, lastname, age);
            
            if (response.getStatus()== Status.CREATED){
                JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            regisUserIDTextField.setText("");
            regisUserFirstnameTextField.setText("");
            regisUserLastnameTextField.setText("");
            regisUserAgeTextField.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_regisUserRegisterButtonActionPerformed

    private void cAccountCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAccountCreateButtonActionPerformed
        // TODO add your handling code here:
        try {
            String userId = cAccountIDTextField.getText();
            String initialBalance = cAccountInitBalanTextField.getText();
            
            Response response = AccountController.createAccount(userId, initialBalance);

            if (response.getStatus() == Status.CREATED) {
                JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            cAccountIDTextField.setText("");
            cAccountInitBalanTextField.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cAccountCreateButtonActionPerformed

    private void mTransacExecuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTransacExecuteButtonActionPerformed
        // TODO add your handling code here:
        try{
            String type = mTransacTypeButton.getItemAt(mTransacTypeButton.getSelectedIndex());
            String sourceAccountId = mTransacSourAccTextField.getText();
            String destinationAccountId = mTransacDestAccTextField.getText();
            String amount = mTransacAmountTextField.getText();
            Response response = new Response("", Status.INTERNAL_SERVER_ERROR);

            switch (type){
                case "Deposit":{
                    response = TransactionController.deposit(destinationAccountId, amount);
                    break;
                }
                case "Withdraw":{
                    response = TransactionController.withdraw(sourceAccountId, amount);
                    break;
                }
                case "Transfer":{
                    response = TransactionController.transfer(sourceAccountId, destinationAccountId, amount);
                    break;
                }
                default: {
                    mTransacSourAccTextField.setText("");
                    mTransacDestAccTextField.setText("");
                    mTransacAmountTextField.setText("");
                    break;
                }
            }
            
            if (response.getStatus() == Status.OK) {
                JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mTransacExecuteButtonActionPerformed

    private void listUsersRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsersRefreshButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listUsersTable.getModel();
        Response response = ListUsersController.refreshUsers(model);
        
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_listUsersRefreshButtonActionPerformed

    private void listAccountsRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAccountsRefreshButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listAccountsTable.getModel();        
        Response response = ListAccountsController.refreshAccounts(model);
        
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_listAccountsRefreshButtonActionPerformed

    private void listTransactioRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTransactioRefreshButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listTransactionsTable.getModel();
        Response response = ListTransactionsController.refreshTransactions(model);
        
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_listTransactioRefreshButtonActionPerformed

    private void regisUserIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisUserIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisUserIDTextFieldActionPerformed

    private void regisUserAgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisUserAgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisUserAgeTextFieldActionPerformed

    private void regisUserLastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisUserLastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisUserLastnameTextFieldActionPerformed

    private void mTransacTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTransacTypeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTransacTypeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cAccountCreateButton;
    private javax.swing.JTextField cAccountIDTextField;
    private javax.swing.JTextField cAccountInitBalanTextField;
    private javax.swing.JLabel createAccountInitialBalanceLabel;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JLabel createAccountUserIDLabel;
    private javax.swing.JLabel listAccountsLabel;
    private javax.swing.JPanel listAccountsPanel;
    private javax.swing.JButton listAccountsRefreshButton;
    private javax.swing.JScrollPane listAccountsScrollPane;
    private javax.swing.JTable listAccountsTable;
    private javax.swing.JButton listTransactioRefreshButton;
    private javax.swing.JLabel listTransactionsLabel;
    private javax.swing.JPanel listTransactionsPanel;
    private javax.swing.JScrollPane listTransactionsScrollPane;
    private javax.swing.JTable listTransactionsTable;
    private javax.swing.JLabel listUsersLabel;
    private javax.swing.JPanel listUsersPanel;
    private javax.swing.JButton listUsersRefreshButton;
    private javax.swing.JScrollPane listUsersScrollPane;
    private javax.swing.JTable listUsersTable;
    private javax.swing.JTextField mTransacAmountTextField;
    private javax.swing.JTextField mTransacDestAccTextField;
    private javax.swing.JButton mTransacExecuteButton;
    private javax.swing.JTextField mTransacSourAccTextField;
    private javax.swing.JComboBox<String> mTransacTypeButton;
    private javax.swing.JLabel makeTransacAmountLabel;
    private javax.swing.JLabel makeTransacDestAccoLabel;
    private javax.swing.JLabel makeTransacSourAccoLabel;
    private javax.swing.JLabel makeTransacTypeLabel;
    private javax.swing.JLabel makeTransactionLabel;
    private javax.swing.JPanel makeTransactionPanel;
    private javax.swing.JTextField regisUserAgeTextField;
    private javax.swing.JTextField regisUserFirstnameTextField;
    private javax.swing.JTextField regisUserIDTextField;
    private javax.swing.JTextField regisUserLastnameTextField;
    private javax.swing.JButton regisUserRegisterButton;
    private javax.swing.JLabel registerUserAgeLabel;
    private javax.swing.JLabel registerUserFirstnameLabel;
    private javax.swing.JLabel registerUserIDLabel;
    private javax.swing.JLabel registerUserLabel;
    private javax.swing.JLabel registerUserLastnameLabel;
    private javax.swing.JPanel registerUserPanel;
    private javax.swing.JTabbedPane tabsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
